apiVersion: v1
kind: Pod
metadata:
  name: poststart-httpget
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - name: http
          containerPort: 80
      lifecycle:
        postStart:
          httpGet:
            host: 10.244.0.9
            port: 8080
            path: /html/index.html
