apiVersion: v1
kind: Pod
metadata:
  name: kiada-init-slow
spec:
  initContainers:
    - name: init-demo
      image: liviumoraru/init-demo:0.1
      args:
        - "60"
    - name: network-check
      image: luksa/network-connectivity-checker:0.1
  containers:
    - name: kiada
      image: liviumoraru/kiada:0.2
      stdin: true
      ports:
        - name: http
          containerPort: 8080
    - name: envoy
      image: liviumoraru/kiada-ssl-proxy:0.1
      ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
